// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function CheckProxy():Promise<string>;

export function Connect(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ExportURI(arg1:string):Promise<string>;

export function GetLogs():Promise<Array<config.LogEntry>>;

export function GetServers():Promise<Array<config.ServerConfig>>;

export function GetSettings():Promise<config.AppSettings>;

export function GetStatus():Promise<config.ConnectionStatus>;

export function GetVersion():Promise<string>;

export function ParseURI(arg1:string):Promise<config.ServerConfig>;

export function Ping(arg1:string):Promise<number>;

export function SaveServer(arg1:config.ServerConfig):Promise<void>;

export function SaveSettings(arg1:config.AppSettings):Promise<void>;
