// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckProxy() {
  return window['go']['main']['App']['CheckProxy']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ParseURI(arg1) {
  return window['go']['main']['App']['ParseURI'](arg1);
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function SaveServer(arg1) {
  return window['go']['main']['App']['SaveServer'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
