// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import type {ServerConfig, AppSettings, ConnectionStatus} from '../../../src/types'

export function CheckProxy(): Promise<string>;
export function Connect(arg1: string): Promise<void>;
export function DeleteServer(arg1: string): Promise<void>;
export function Disconnect(): Promise<void>;
export function GetServers(): Promise<ServerConfig[]>;
export function GetSettings(): Promise<AppSettings>;
export function GetStatus(): Promise<ConnectionStatus>;
export function Ping(arg1: string): Promise<number>;
export function SaveServer(arg1: ServerConfig): Promise<void>;
export function SaveSettings(arg1: AppSettings): Promise<void>;